# Generated by Django 3.1.1 on 2021-03-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisor',
            old_name='posion',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member',
        ),
        migrations.AddField(
            model_name='project',
            name='member',
            field=models.ManyToManyField(to='projects.Member'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='task',
        ),
        migrations.AddField(
            model_name='project',
            name='task',
            field=models.ManyToManyField(to='projects.Task'),
        ),
    ]
