# Generated by Django 3.1.1 on 2021-03-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210316_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='image',
        ),
        migrations.RemoveField(
            model_name='task',
            name='member',
        ),
        migrations.AddField(
            model_name='task',
            name='member',
            field=models.ManyToManyField(to='projects.Member'),
        ),
    ]
