# Generated by Django 3.1.1 on 2021-04-09 10:27

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210330_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='task',
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='symbol_no',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31, unique=True),
        ),
    ]
