# Generated by Django 3.1.1 on 2021-04-09 10:39

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210409_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
