# Generated by Django 3.1.1 on 2021-04-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210409_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor',
            field=models.ManyToManyField(to='projects.Supervisor'),
        ),
    ]
