# Generated by Django 3.1.1 on 2021-04-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210409_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='member',
        ),
        migrations.AddField(
            model_name='member',
            name='task',
            field=models.ManyToManyField(to='projects.Task'),
        ),
    ]
